<p>
Este site é um teste básico de código PHP utilizando Zend Framework, JQuery e Layout960, para demonstrar minhas aptidões como programador.<br/>
Qualquer pessoa que se interessar pelo código copia-lo.<br/>
Serão feitas novas implementações de acordo com o meu estudo.
</p>
<p>
O planejamento utilizando o Redmine, encontra-se em <a href="http://dev.zed.net.br/projects/testebasicoadm/issues">Projeto Admissão</a>
</p>
<p>
O código deste sistema encontra-se em 
</p>
