<p>
Este site é um teste básico de código PHP utilizando Zend Framework, JQuery e Layout960, para demonstrar minhas habilidades como programador.<br/>
Qualquer pessoa que tiver interesse pelo código, tem a atorização de copia-lo.<br/>
Serão feitas novas implementações de acordo com o meu estudo.
</p>
<p>
O planejamento utilizando o Redmine, encontra-se em <a href="http://dev.zed.net.br/projects/testebasicoadm/issues">Projeto Admissão</a>
</p>
<p>
O código deste sistema encontra-se em <a href="https://github.com/zedmaster/testeadmissional">GitHub</a>
</p>

<style>
.logos{text-align: center; margin-top: 50px;}
.logos a{ margin: 10px;}
</style>
<div class="logos">
   <a href="http://php.net/" target="_new"><img src="/style/01/img/php.png"></a>
   <a href="http://framework.zend.com/" target="_new"><img src="/style/01/img/zendframework.png"></a>
   <a href="http://jquery.com/" target="_new"><img src="/style/01/img/jquery.png"></a>
   <a href="http://960.gs/" target="_new"><img src="/style/01/img/960.png"></a>
</div>
