<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php $this->headLink()
                           ->prependStylesheet('/css/reset.css')
                           ->appendStylesheet('/style/01/default.css')
                           ->appendStylesheet('/css/text.css')
                           ->appendStylesheet('/css/960_24_col.css')
                           ->appendStylesheet('/css/cupertino/jquery-ui-1.8.18.custom.css');
    ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->jQuery()
                    ->setVersion('1.7.1')
                    ->setUiVersion('1.8.18')
                    ->addJavascriptFile('/js/jquery.dataTables.min.js')
                    ->addJavascript("$(document).ready(function(){ $('#table1').dataTable({'bJQueryUI': true}); });");
    ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>
    <?php echo $this->render('header.phtml') ?>

    <div class="container_24">
        <div id="nav" class="grid_24"><?php echo $this->placeholder('nav') ?></div>
    </div>

    <div class="container_24 ui-tabs-panel ui-widget-content ui-corner-bottom" id="container">
        <div class="grid_24">
            <?php echo $this->layout()->content ?>
        </div>
    </div>

    <div class="container_24" id="footer">
        <div id="cms" class="grid_12">
            <?php echo $this->render('footer.phtml') ?>
        </div>
        <div id="feeds" class="grid_12">
        </div>
    </div>
</body>
</html>
