<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php $this->headLink()
                           ->prependStylesheet('/css/reset.css')
                           ->appendStylesheet('/style/01/default.css')
                           ->appendStylesheet('/css/text.css')
                           ->appendStylesheet('/css/960_24_col.css');
    ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->jQuery(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headStyle(); ?>
</head>
<body>
    <?php echo $this->render('header.phtml') ?>

    <div class="container_24">
        <div id="nav" class="grid_24">
           <a href="/">Home</a> 
           <a href="/usuario">Usuário</a> 
        </div>
    </div>

    <div class="container_24 ui-tabs-panel ui-widget-content ui-corner-bottom" id="container">
        <div class="prefix_1 grid_22">
            <?php echo $this->layout()->content ?>
        </div>
    </div>

    <div class="container_24" id="footer">
        <div id="cms" class="grid_2 prefix_22">
            <?php echo $this->render('footer.phtml') ?>
        </div>
    </div>
</body>
</html>
